name: now
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  collection: ^1.16.0

dev_dependencies:
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  grinder: ^0.9.3
  test: ^1.23.1


