name: now
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # freezed_annotation: ^2.0.3
  # json_annotation: ^4.6.0
  dio: ^5.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  # build_runner: ^2.1.11
  json_serializable: ^6.2.0


